### ISSUE TITLE
Add unlisted dependencies to `README.md` file

### ISSUE THREAD

**Issue by H4ppy-04** [nednoodlehead/punge#13]
**Issue**
Before running `cargo install`, I had to install [libasound2-dev](https://github.com/alsa-project/alsa-lib), which was not listed in the `README.md` requirements.

**Suggest changes**
Add a dependencies section to `README.md` or modify the existing requirements section to list this dependency.

**Comment by nednoodlehead** [comment]
what os are you on? I've built it on win11, win10 and ubuntu without installing that

**Comment by H4ppy-04** [comment]
> What os are you on? I've built it on win11, win10 and Ubuntu without installing that

That's odd. I'm on Ubuntu 22.04.4 LTS.

**Comment by nednoodlehead** [comment]
ngl you probably right. i think i remember installing that. ill separate the build into windows vs ubuntu install, and if others have issues they can raise it and i can add the dependancies. dont feel like booting up a vm for all the common distros lol, least not yet.
