### ISSUE TITLE
add song-in-list support

### ISSUE THREAD

**Issue by nednoodlehead** [nednoodlehead/punge#5]
gotta wait for iced to release the list widget (why is the infinite scroller not dynamic rendering idk)

**Comment by H4ppy-04** [comment]
The [`pick_list`](https://docs.rs/iced/latest/iced/widget/pick_list/index.html) component was introduced in https://github.com/iced-rs/iced/commit/d23026d2dd24ae6daa20f479678ad802f493c7bc if that's what you mean.

**Comment by nednoodlehead** [comment]
No more like a QTableWidget, to display all of the songs. I'll make a few changes today that should address this.

It has been the main problem with this project anyways, since iced doesn't have a widget to dynamically render content properly, I'm using [tarkah's table](https://github.com/tarkah/iced_table). Which depends on the `scrollable`, which should get that dynamic rendering fix soon.

So right now my punge has 1500 entries, and it lags a little bit, and has high cpu usage when scrolling, but its better than nothing.
