### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by larkinxp** [nednoodlehead/punge#74]
Fresh clone of this repository nd followed the instructions in the readme.

```
[u@DESKTOP-5E8NBQ5 punge]$ cp ./target/release/punge .
[u@DESKTOP-5E8NBQ5 punge]$ ./punge
thread 'main' panicked at src/player/player_cache.rs:17:60:
called `Result::unwrap()` on an `Err` value: Error("missing field `length`", line: 1, column: 61)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by nednoodlehead** [comment]
Right, I keep forgetting to fix that. It is just a missing field in the cached json. ill send a fix

**Comment by nednoodlehead** [comment]
should be fixed with this patch:
https://github.com/nednoodlehead/punge/commit/491fd26571eab9a4b3475b5e8ad988ee4b04a65f
